[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "model-service"
version = "0.0.1"
dependencies = []

[tool.setuptools]
packages = ["model_service"]

[project.scripts]
model-service = "model_service.train:main"
